-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgL+pinKDOH96IOYkH
sqcqa1WiLgLLqgVULFJoKcc+IZKgCgYIKoZIzj0DAQehRANCAAS3XPbB3MP6LSPk
AhQYz2z+r9FfkY0/aUFrU10C0rxOHAlZ0tfy+PdxohTNY7CrmxWA0Iz6vLFTUsUV
93DkUGG7
-----END PRIVATE KEY-----